#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd -- "$SCRIPT_DIR"

if [ ! -f .env ]
then
  cp .env.example .env
fi

source .env


docker buildx build \
  -f Dockerfile.dev \
  -t "$SPAXION_IMAGE" \
  .

docker run \
  -it \
  --rm \
  --env DISPLAY="$SPAXION_DISPLAY" \
  --device "$SPAXION_SOUND" \
  --mount "type=bind,source=$(pwd),target=/usr/src/app" \
  --mount "type=bind,source=${SPAXION_X11},target=/tmp/.X11-unix/" \
  --user "$(id -u):$(id -g)" \
  "$SPAXION_IMAGE" bash
